id = "neocmake"
name = "NeoCMake"
version = "0.1.1"
schema_version = 1
authors = ["Sorochan Ilya <sorochanilyav@gmail.com>"]
description = "CMake grammar and lsp with neocmakelsp"
repository = "https://github.com/k0tran/zed_neocmake"

[language_servers.cmake]
name = "neocmakelsp"
language = "CMake"

[grammars.cmake]
repository = "https://github.com/uyha/tree-sitter-cmake"
commit = "c51df182f951955bd93189abe5591ed73b5f49d6"      # v0.7.2
