id = "neocmake"
name = "NeoCMake"
version = "0.0.5"
schema_version = 1
authors = ["Sorochan Ilya <sorochanilyav@gmail.com>"]
description = "CMake grammar and lsp with neocmakelsp"
repository = "https://github.com/k0tran/zed_neocmake"

[language_servers.cmake]
name = "neocmakelsp"
language = "CMake"

[grammars.cmake]
repository = "https://github.com/uyha/tree-sitter-cmake"
commit = "cd00bbcb77fe31283ca79b0038387ec7411759ae"      # v0.6.1
